In [1]:
#importing pandas 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#reading the dataset

data=pd.read_csv("train.csv")

In [3]:
#dimensions of the dataset

data.shape

(8523, 12)

In [4]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [5]:
data=pd.get_dummies(data)

In [6]:
#making the train dataset 

train=data[0:7999]

In [9]:
#making the test dataset

test=data[8000:]
test.shape

(523, 1605)

In [8]:
test.head()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales,Item_Identifier_DRA12,Item_Identifier_DRA24,Item_Identifier_DRA59,Item_Identifier_DRB01,Item_Identifier_DRB13,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
8000,7.02,0.081329,150.0734,2002,4454.2020,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8001,7.42,0.020388,247.1092,2004,4233.1564,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8002,17.25,0.113518,253.5724,1997,5033.4480,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
8003,18.75,0.052917,190.6504,2002,1342.2528,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8004,20.25,0.018911,220.5772,2007,2446.1492,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0

In [10]:
test.columns

Index(['Item_Weight', 'Item_Visibility', 'Item_MRP',
       'Outlet_Establishment_Year', 'Item_Outlet_Sales',
       'Item_Identifier_DRA12', 'Item_Identifier_DRA24',
       'Item_Identifier_DRA59', 'Item_Identifier_DRB01',
       'Item_Identifier_DRB13',
       ...
       'Outlet_Size_High', 'Outlet_Size_Medium', 'Outlet_Size_Small',
       'Outlet_Location_Type_Tier 1', 'Outlet_Location_Type_Tier 2',
       'Outlet_Location_Type_Tier 3', 'Outlet_Type_Grocery Store',
       'Outlet_Type_Supermarket Type1', 'Outlet_Type_Supermarket Type2',
       'Outlet_Type_Supermarket Type3'],
      dtype='object', length=1605)

In [11]:
x_train=train.drop('Item_Outlet_Sales', axis=1)

In [36]:
x_train

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Identifier_DRA12,Item_Identifier_DRA24,Item_Identifier_DRA59,Item_Identifier_DRB01,Item_Identifier_DRB13,Item_Identifier_DRB24,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,9.30,0.016047,249.8092,1999,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
1,5.92,0.019278,48.2692,2009,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
2,17.50,0.016760,141.6180,1999,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
3,19.20,0.000000,182.0950,1998,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
4,8.93,0.000000,53.8614,1987,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7994,10.50,0.027276,171.3106,1997,0,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
7995,12.85,0.152748,252.0382,2009,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
7996,0.00,0.060707,127.5020,1985,0,0,0,0,0,0,...,0,0,1,1,0,0,1,0,0,0
7997,6.36,0.120788,45.7060,2002,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
7998,0.00,0.076852,111.8570,1985,0,0,0,0,0,0,...,0,0,1,1,0,0,1,0,0,0

In [12]:
y_train=train['Item_Outlet_Sales']

In [13]:
x_test=test.drop('Item_Outlet_Sales', axis=1)

In [14]:
true_p=test['Item_Outlet_Sales']

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
lreg=LinearRegression()

In [26]:
lreg.fit(x_train,y_train)

LinearRegression()

In [27]:
x_train.fillna(0,inplace=True)

In [28]:
x_test.fillna(0,inplace=True)

In [31]:
pred=lreg.predict(x_test)

In [32]:
pred

array([ 2.4110e+03,  3.8860e+03,  3.8490e+03,  2.0695e+03,  4.7590e+03,
        2.9940e+03,  1.8815e+03,  2.5100e+03,  3.5240e+03,  5.3375e+03,
        4.8685e+03,  1.0990e+03,  4.1410e+03,  9.3550e+02,  1.6855e+03,
        9.3800e+02,  5.4900e+02,  9.3150e+02,  3.4785e+03,  2.2285e+03,
        1.9805e+03,  2.1850e+03,  3.8095e+03,  5.3740e+03,  1.2210e+03,
       -8.5950e+02,  2.5590e+03,  2.5645e+03,  5.0355e+03,  4.2085e+03,
        6.3250e+02,  3.0350e+02,  1.0355e+03,  1.5375e+03,  1.4530e+03,
        2.6325e+03,  2.9075e+03,  1.3975e+03,  6.2000e+02,  4.8180e+03,
        2.9355e+03,  1.0650e+03,  3.6615e+03,  2.4250e+02,  3.4470e+03,
        1.8840e+03,  3.1485e+03,  2.5905e+03,  7.9700e+02,  6.2750e+02,
        5.4880e+03,  2.3430e+03,  2.4750e+03,  2.2645e+03,  1.1650e+02,
        2.9395e+03,  2.4585e+03,  1.6025e+03,  7.8500e+02,  3.7995e+03,
        2.0100e+02,  2.8410e+03,  2.4880e+03, -4.3400e+02,  4.8715e+03,
        2.5770e+03,  2.7115e+03,  2.9655e+03,  2.1055e+03,  2.6050e+03,
        2.0110e+03,  2.0515e+03,  3.3550e+03,  2.1175e+03,  2.7975e+03,
        2.8905e+03,  2.2755e+03,  1.8735e+03,  3.0865e+03,  2.4675e+03,
        2.6355e+03,  1.7065e+03,  2.0510e+03,  2.9590e+03,  2.8690e+03,
        1.8300e+03,  4.2520e+03,  3.8985e+03,  1.8360e+03,  3.1800e+03,
       -7.4350e+02,  7.1950e+02,  1.4525e+03,  1.0635e+03, -5.0600e+02,
        3.0215e+03,  1.1720e+03,  8.6450e+02,  4.3000e+03,  4.4975e+03,
        3.0120e+03,  4.9605e+03,  2.9360e+03,  5.0000e+00,  2.3335e+03,
        1.7485e+03,  7.9600e+02,  5.6400e+02,  1.5120e+03,  3.4155e+03,
       -9.8950e+02,  9.9150e+02,  1.5135e+03,  2.5610e+03,  1.3290e+03,
        9.6050e+02, -1.1480e+03,  4.0935e+03,  9.3400e+02,  1.7350e+03,
        2.4170e+03,  3.5200e+02,  1.4845e+03,  3.2445e+03,  1.0945e+03,
        4.7640e+03,  2.3840e+03,  3.8280e+03,  3.7740e+03,  2.6375e+03,
        1.5570e+03,  4.3725e+03,  2.1910e+03,  6.2100e+02,  1.0755e+03,
        5.7050e+02,  4.2525e+03,  2.2850e+03,  2.8205e+03,  1.8805e+03,
        8.4100e+02,  6.5800e+02,  3.0275e+03,  1.4655e+03,  4.0160e+03,
        2.3915e+03,  4.7635e+03,  3.2785e+03,  3.6990e+03,  2.1130e+03,
        1.1590e+03,  1.8820e+03, -9.0200e+02,  3.9435e+03,  4.2715e+03,
        4.9350e+02,  1.1490e+03,  2.5900e+03,  2.1470e+03,  2.0695e+03,
        2.7540e+03,  3.7720e+03,  8.8850e+02,  4.7375e+03,  2.9040e+03,
        5.4180e+03,  4.9850e+02,  2.5595e+03,  1.1325e+03,  2.6750e+03,
        4.9425e+03,  1.9860e+03,  3.8460e+03,  1.2715e+03,  3.3065e+03,
        4.5580e+03,  1.6310e+03,  6.0115e+03,  5.0775e+03,  1.2040e+03,
        2.6765e+03,  2.8445e+03,  2.0325e+03,  1.4715e+03,  3.8590e+03,
        1.9435e+03,  3.7130e+03,  1.4635e+03,  1.9490e+03,  1.1565e+03,
        2.9360e+03,  1.2220e+03,  2.1910e+03,  2.2060e+03,  2.4900e+02,
        2.2335e+03,  2.6435e+03,  1.5655e+03,  5.7245e+03,  5.1740e+03,
        3.1215e+03,  5.0610e+03,  1.4410e+03,  2.0110e+03,  4.7300e+02,
        1.1725e+03,  5.9450e+02,  2.9010e+03,  4.3795e+03,  1.5155e+03,
        4.9755e+03,  1.9890e+03,  2.9755e+03,  1.5830e+03,  2.1960e+03,
        1.9095e+03,  2.7365e+03,  3.3350e+03,  1.7805e+03,  1.5370e+03,
        1.9825e+03,  1.8485e+03,  3.4620e+03,  1.2825e+03,  4.4990e+03,
        2.3185e+03,  3.0650e+02,  6.5100e+02,  1.3830e+03,  2.6850e+03,
        3.6250e+02,  3.3455e+03,  2.9540e+03,  1.9520e+03, -6.2000e+01,
        5.7400e+02,  2.6065e+03, -1.1350e+02,  1.4515e+03, -1.9460e+03,
        1.2070e+03, -1.2115e+03,  1.6960e+03,  3.7485e+03,  5.4525e+03,
        5.0790e+03,  1.7745e+03,  1.4765e+03,  3.3300e+02,  4.2310e+03,
        2.1890e+03,  5.6205e+03,  3.3705e+03,  1.0415e+03,  2.0695e+03,
        2.0660e+03,  1.7445e+03,  1.8590e+03,  1.4625e+03,  9.6850e+02,
        1.1265e+03,  2.7300e+03,  2.0185e+03,  3.4005e+03,  3.7065e+03,
        2.6055e+03,  7.1500e+02,  3.4205e+03,  1.0590e+03, -9.6800e+02,
        2.3350e+03,  2.3075e+03,  1.7755e+03,  8.9400e+02,  3.7875e+03,
        1.6260e+03,  1.3270e+03,  6.8950e+02,  3.4245e+03,  3.0885e+03,
        3.1395e+03,  4.5400e+03,  2.4515e+03,  1.4785e+03,  4.7000e+01,
        2.2740e+03,  1.7090e+03,  7.0100e+02,  3.0800e+02,  1.6420e+03,
        8.1850e+02,  4.2250e+02,  1.4680e+03,  1.3025e+03,  1.4715e+03,
        3.6545e+03, -8.9850e+02,  1.7235e+03,  1.3225e+03,  2.3385e+03,
        1.3035e+03,  4.2045e+03,  1.4620e+03,  3.8825e+03,  3.7820e+03,
        3.2130e+03,  1.6300e+03,  9.6300e+02,  4.2020e+03,  2.4580e+03,
        2.2635e+03,  2.2370e+03,  5.0770e+03,  2.3375e+03,  9.7650e+02,
        2.2320e+03,  1.3475e+03,  1.3145e+03,  1.2770e+03,  4.0105e+03,
        2.7875e+03,  3.8585e+03,  5.8870e+03,  2.1360e+03,  1.9030e+03,
        7.3450e+02,  2.8765e+03,  2.9835e+03,  3.2830e+03,  5.2190e+03,
        1.2705e+03,  4.7195e+03,  7.9750e+02,  1.5780e+03,  1.4865e+03,
        1.0805e+03,  1.3500e+02,  8.8900e+02,  1.7535e+03,  2.2660e+03,
        2.7505e+03,  1.5560e+03,  4.0195e+03,  1.8800e+03,  3.9965e+03,
        2.0770e+03,  2.6335e+03,  1.5435e+03,  9.8300e+02,  3.3895e+03,
        3.8300e+03,  4.2745e+03,  6.3300e+02,  1.2790e+03,  2.7980e+03,
        2.3765e+03,  4.7425e+03,  2.1230e+03, -1.9100e+02,  4.5000e+00,
        3.8585e+03,  2.9550e+03,  4.3930e+03,  2.8340e+03,  1.9605e+03,
        2.5300e+02,  6.6150e+02,  1.2400e+03,  2.5565e+03,  2.3025e+03,
        2.6845e+03,  1.0665e+03,  2.6435e+03,  2.7310e+03,  7.6850e+02,
        3.4950e+03,  4.9150e+03,  2.4235e+03,  1.8440e+03,  3.0600e+03,
        4.0505e+03,  3.2065e+03,  2.0790e+03,  5.0975e+03,  8.3000e+02,
        1.6715e+03,  8.9000e+02,  1.0700e+03,  1.9375e+03,  1.7320e+03,
        7.6800e+02,  1.7905e+03,  1.6700e+03,  4.3850e+02,  1.8245e+03,
        2.4630e+03,  1.1730e+03,  7.9200e+02,  1.4175e+03, -9.5050e+02,
       -3.3900e+02,  1.5255e+03,  2.1340e+03,  4.5615e+03, -3.6000e+02,
       -5.6750e+02,  1.5095e+03,  2.7705e+03,  4.7555e+03,  2.6080e+03,
        3.6680e+03,  3.4330e+03,  3.0370e+03,  1.5915e+03,  1.7795e+03,
        2.4065e+03,  9.5850e+02,  8.2400e+02,  8.8100e+02,  2.4015e+03,
        1.4105e+03,  2.2365e+03,  2.1130e+03,  3.5120e+03,  3.6275e+03,
        2.2450e+03,  2.9870e+03,  1.1975e+03,  2.5745e+03,  2.9445e+03,
        2.3185e+03,  9.6600e+02, -1.0260e+03,  2.6765e+03,  2.3480e+03,
        5.0225e+03,  9.2200e+02,  1.8925e+03,  2.2020e+03,  1.8780e+03,
        1.7235e+03,  2.0615e+03, -9.9800e+02,  1.7325e+03,  3.3175e+03,
        3.2000e+02,  9.0200e+02,  4.0125e+03,  1.2645e+03,  8.9500e+01,
        1.3610e+03,  4.3460e+03,  2.2595e+03,  4.2825e+03,  4.9150e+02,
        2.9740e+03,  1.7260e+03,  1.8685e+03,  1.5165e+03,  1.6795e+03,
        2.3565e+03,  3.3715e+03,  1.0990e+03,  1.9505e+03,  1.9625e+03,
        3.1490e+03,  3.2200e+02,  1.3585e+03,  8.7800e+02,  9.8600e+02,
        2.2835e+03,  1.7880e+03,  3.7810e+03,  6.6150e+02,  1.3335e+03,
        2.3140e+03,  1.8190e+03,  3.3060e+03,  2.1365e+03,  1.4055e+03,
        2.4150e+02,  9.6700e+02,  1.9610e+03,  1.7130e+03,  2.0370e+03,
        5.3335e+03, -1.1595e+03,  5.1845e+03,  4.0145e+03,  9.4900e+02,
        1.0100e+03,  3.3115e+03,  1.5255e+03,  3.5760e+03,  1.9225e+03,
        2.2525e+03,  3.9195e+03,  2.5120e+03,  1.9450e+03,  2.0905e+03,
        2.4280e+03,  1.5080e+03,  1.6570e+03,  2.4360e+03,  4.0980e+03,
        4.0550e+03,  2.9155e+03,  1.5955e+03,  2.0685e+03,  2.9750e+03,
        4.7095e+03,  4.0815e+03,  2.0145e+03,  1.6240e+03,  1.1070e+03,
        2.3030e+03,  1.2355e+03,  3.3960e+03,  3.7575e+03,  2.9015e+03,
        1.1035e+03,  1.7635e+03,  1.4020e+03])

In [33]:
x_test

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Identifier_DRA12,Item_Identifier_DRA24,Item_Identifier_DRA59,Item_Identifier_DRB01,Item_Identifier_DRB13,Item_Identifier_DRB24,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
8000,7.020,0.081329,150.0734,2002,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8001,7.420,0.020388,247.1092,2004,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8002,17.250,0.113518,253.5724,1997,0,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
8003,18.750,0.052917,190.6504,2002,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8004,20.250,0.018911,220.5772,2007,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,6.865,0.056783,214.5218,1987,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
8519,8.380,0.046982,108.1570,2002,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8520,10.600,0.035186,85.1224,2004,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8521,7.210,0.145221,103.1332,2009,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
8522,14.800,0.044878,75.4670,1997,0,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0

In [34]:
true_p

8000    4454.2020
8001    4233.1564
8002    5033.4480
8003    1342.2528
8004    2446.1492
          ...
8518    2778.3834
8519     549.2850
8520    1193.1136
8521    1845.5976
8522     765.6700
Name: Item_Outlet_Sales, Length: 523, dtype: float64

In [35]:
#performance of our model -r2

lreg.score(x_test,true_p)

0.40227153690776773

In [37]:
lreg.score(x_train,y_train)

0.6497735631845378

In [38]:
rmse_test = np.sqrt(np.mean(np.power((np.array(true_p)-np.array(pred)),2)))

In [39]:
rmse_train = np.sqrt(np.mean(np.power((np.array(y_train)-np.array(lreg.predict(x_train))),2)))

In [40]:
print(rmse_train)
print(rmse_test)

1013.0040784390595
1255.3981735645664